import test from 'node:test';import assert from 'node:assert/strict';import {fetchJson} from '../services/http.js';import {fetchThreats} from '../services/threats.js';import {fetchMapa} from '../services/mapa.js';import {normalizeNeptun,normalizeMapa} from '../services/normalize.js';import {shouldPoll,POLL_MS} from '../services/data.js';
const originalFetch=globalThis.fetch;
test.afterEach(()=>{globalThis.fetch=originalFetch});
test('HTTP errors are surfaced without malformed parsing',async()=>{globalThis.fetch=async()=>new Response('fail',{status:500});await assert.rejects(fetchJson('https://example.invalid'),/HTTP 500/)});
test('malformed JSON is rejected',async()=>{globalThis.fetch=async()=>new Response('{bad',{status:200});await assert.rejects(fetchJson('https://example.invalid'),/Некоректний JSON/)});
test('threat adapter removes invalid coordinates and duplicates',async()=>{globalThis.fetch=async()=>new Response(JSON.stringify({serverTime:'2026-10-02T20:00:00Z',threats:[{id:'a',type:'uav',lat:50,lon:30,status:'active',updatedAt:'2026-10-02T20:00:00Z'},{id:'a',type:'uav',lat:50,lon:30,status:'active',updatedAt:'2026-10-02T20:00:00Z'},{id:'b',type:'uav',lat:99,lon:30,status:'active'}]}),{status:200});const r=await fetchThreats();assert.equal(r.threats.length,2);assert.equal(r.threats.find(x=>x.id==='b').hasPoint,false)});
test('trackId is the source-stable id, never invented or shared across sources',()=>{const a=normalizeNeptun({id:'7',type:'uav',title:'БпЛА',lat:50,lon:31,updatedAt:'2026-10-05T20:00:00Z'},new Date('2026-10-05T20:00:10Z'));const b=normalizeMapa({id:7,kind:'uav',status:'active',lat:50,lon:31,last_seen:1759694410},new Date('2026-10-05T20:00:10Z'));assert.equal(a.trackId,'neptun:7');assert.equal(a.trackId,a.id);assert.equal(b.trackId,'mapa:7');assert.equal(b.trackId,b.id);assert.notEqual(a.trackId,b.trackId);assert.equal(normalizeNeptun({id:'7',type:'uav',title:'БпЛА',lat:50.1,lon:31.1,updatedAt:'2026-10-05T20:01:00Z'}).trackId,'neptun:7')});
test('mapa adapter dedupes repeated source rows by id before render',async()=>{globalThis.fetch=async()=>new Response(JSON.stringify({ts:1759694410,objects:[{id:1,kind:'uav',status:'active',lat:50,lon:31,last_seen:1759694410},{id:1,kind:'uav',status:'active',lat:50,lon:31,last_seen:1759694410},{id:2,kind:'uav',status:'active',lat:51,lon:32,last_seen:1759694410}]}),{status:200});const r=await fetchMapa();assert.equal(r.events.length,2);assert.deepEqual(r.events.map(e=>e.id),['mapa:1','mapa:2'])});
test('shouldPoll gates auto-refresh on visibility, setting, overlap and interval',()=>{assert.equal(POLL_MS,45000);const base={hidden:false,autoRefresh:true,loading:false,lastStart:0,nowMs:45000};assert.equal(shouldPoll(base),true);assert.equal(shouldPoll({...base,hidden:true}),false);assert.equal(shouldPoll({...base,autoRefresh:false}),false);assert.equal(shouldPoll({...base,loading:true}),false);assert.equal(shouldPoll({...base,nowMs:44999}),false);assert.equal(shouldPoll(),true)});
