import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
test('PWA metadata and relative paths',()=>{const m=JSON.parse(read('manifest.webmanifest'));assert.equal(m.name,'Небо.UA');assert.equal(m.display,'standalone');assert.equal(m.start_url,'./');assert.match(read('assets/js/app.js'),/serviceWorker\.register\('\.\/service-worker\.js'\)/)});
test('production source has no fake threat arrays',()=>{const all=['assets/js/app.js','services/threats.js'].map(read).join('\n');assert.doesNotMatch(all,/const\s+(drones|missiles)\s*=\s*\[/i)});
test('service worker does not cache API',()=>assert.match(read('service-worker.js'),/includes\('\/api\/'\).*return/));
test('required safety copy exists',()=>{const h=read('index.html');assert.match(h,/не замінює офіційні системи/);assert.match(h,/моніторингові повідомлення відображаються окремо/);assert.match(h,/не є прямим каналом державного API/)})
test('region-only selection clears stale detailed location',()=>{const app=read('assets/js/app.js'),enhancements=read('assets/js/enhancements.js');assert.match(app,/if\(!preservePlace\)\{localStorage\.removeItem\('nebo-location'\)/);assert.match(enhancements,/preservePlace:true/)})
test('fresh-only preference also filters the threat list',()=>assert.match(read('assets/js/app.js'),/function renderThreats\(\)\{const available=flowEvents\(\)/))
test('district focus is absent until the user selects a region',()=>assert.match(read('assets/js/app.js'),/if\(!saved\|\|!names\.includes\(saved\)\)return''/))
test('first live snapshot primes the timeline without fake changes',()=>assert.match(read('assets/js/app.js'),/if\(!state\.timelinePrimed\)\{state\.previous=next;state\.timelinePrimed=true;return\}/))
test('PWA has shortcuts and compact widget view',()=>{const m=JSON.parse(read('manifest.webmanifest'));assert.equal(m.shortcuts.length,4);assert.match(read('widget/index.html'),/не системний віджет/)});
test('map markers use dedicated threat SVGs and source-only heading',()=>{const map=read('assets/js/map.js');assert.match(map,/threat-icons\.svg/);assert.match(map,/Number\.isFinite\(e\.heading\)/);assert.doesNotMatch(map,/predicted|dead reckoning/i)});
test('SEO basics for indexing',()=>{const h=read('index.html');assert.match(h,/<title>[^<]+<\/title>/);assert.match(h,/name="description"/);assert.match(h,/rel="canonical" href="https:\/\/movchan-educatio\.github\.io\/nebo-ua\/"/);assert.match(h,/application\/ld\+json/);assert.match(read('robots.txt'),/Sitemap: https:\/\/movchan-educatio\.github\.io\/nebo-ua\/sitemap\.xml/);assert.match(read('sitemap.xml'),/<loc>https:\/\/movchan-educatio\.github\.io\/nebo-ua\/<\/loc>/)});
