import{fetchAlerts}from'./alerts.js';import{fetchThreats}from'./threats.js';import{fetchMapa}from'./mapa.js';import{fetchAggregated}from'./aggregator.js';import{DATA_MODE}from'./config.js';import{normalizeAlert,normalizeNeptun,isFresh}from'./normalize.js';import{correlate,fuse,detectDisagreement}from'./correlation.js';
export async function fetchAll(signal){if(DATA_MODE==='aggregator'){try{return await fetchAggregated(signal)}catch(e){console.warn('Aggregator unavailable, falling back to direct fetch',e)}}const receivedAt=new Date(),tasks=await Promise.allSettled([fetchAlerts(signal),fetchThreats(signal),fetchMapa(signal)]);const health={OFFICIAL:healthItem(tasks[0]),NEPTUN:healthItem(tasks[1],tasks[1].status==='fulfilled'&&tasks[1].value.stale),MAPA:healthItem(tasks[2])};const alerts=tasks[0].status==='fulfilled'?tasks[0].value.map(x=>normalizeAlert(x,receivedAt)).filter(Boolean):[];const neptun=tasks[1].status==='fulfilled'?tasks[1].value.threats.map(x=>normalizeNeptun(x,receivedAt)).filter(Boolean):[];const mapa=tasks[2].status==='fulfilled'?tasks[2].value.events:[];const events=[...neptun,...mapa].map(e=>({...e,stale:e.stale||!isFresh(e)}));const correlated=correlate(events);const fused=fuse(correlated);return{alerts,events:fused,rawEvents:events,health,disagreement:detectDisagreement(events,health),receivedAt};}
function healthItem(r,delayed=false){return r.status==='fulfilled'?{status:delayed?'delayed':'online',updatedAt:new Date(),error:delayed?'Джерело позначило потік як застарілий':null}:{status:'offline',updatedAt:null,error:r.reason?.message||'Недоступно'}}
export function getOfficialAlert(snapshot,region){return snapshot.alerts.filter(a=>a.region===region)}
export const POLL_MS=45000;
export function shouldPoll({hidden=false,autoRefresh=true,loading=false,lastStart=0,nowMs=Date.now(),intervalMs=POLL_MS}={}){
  if(hidden||!autoRefresh||loading)return false;
  return nowMs-lastStart>=intervalMs;
}export function getActiveThreats(snapshot,region){return snapshot.events.filter(e=>!region||e.region===region||e.derivedRegion===region)}export function getSourceHealth(snapshot){return snapshot.health}export function getRegionStatus(snapshot,region){return{official:getOfficialAlert(snapshot,region),monitoring:getActiveThreats(snapshot,region),updatedAt:snapshot.receivedAt}}export function getRecentChanges(timeline,region){return timeline.filter(x=>!region||x.region===region).slice(0,20)}
