import{eventRelevance,RELEVANCE}from'./relevance.js';import{raionAlertActive}from'./districts.js';
export const NOTIFICATION_CATEGORIES=Object.freeze({OFFICIAL_ALERT_START:'official-alert-start',OFFICIAL_ALERT_END:'official-alert-end',UAV:'uav',MISSILE:'missile',KAB:'kab',AVIATION:'aviation'});
export const DEFAULT_NOTIFICATION_PREFS={enabled:false,officialStart:true,officialEnd:true,uav:true,missile:true,kab:true,aviation:true,myOblast:true,myRaion:true,mySettlement:true,quietNight:false};
const PREF='nebo-notification-preferences-v1',BASE='nebo-notification-baseline-v1';
export function fingerprint(event){return`${event.source||'source'}:${event.sourceEventId||event.id}:${event.category}`}
export function deriveNotificationCandidates(previous,current,place,prefs=DEFAULT_NOTIFICATION_PREFS){if(!previous||!place||!prefs.enabled)return[];const region=place.oblast,out=[],prevScope=raionAlertActive(previous.alerts,region,place.raion),curScope=raionAlertActive(current.alerts,region,place.raion),before=!!prevScope&&prevScope.scope!=='outside',after=!!curScope&&curScope.scope!=='outside',officialKnown=current.health?.OFFICIAL?.status!=='offline',scopeName=place.raion?place.raion+' район, '+region:region;if(!before&&after&&prefs.officialStart&&officialKnown)out.push({type:'officialStart',official:true,title:'Повітряна тривога',body:scopeName,id:`official:start:${region}:${place.raion||''}`});if(before&&!after&&prefs.officialEnd&&officialKnown)out.push({type:'officialEnd',official:true,title:'Відбій повітряної тривоги',body:scopeName,id:`official:end:${region}:${place.raion||''}`});const old=new Set((previous.events||[]).map(fingerprint));for(const e of current.events||[]){if(old.has(fingerprint(e)))continue;const type=e.category==='ballistic'?'missile':e.category;if(!['uav','missile','kab','aviation'].includes(type)||!prefs[type])continue;const relevance=eventRelevance(e,place),allowed=relevance===RELEVANCE.DIRECT&&prefs.mySettlement||relevance===RELEVANCE.RAION&&prefs.myRaion||relevance===RELEVANCE.OBLAST&&prefs.myOblast;if(!allowed)continue;out.push({type,official:false,title:`${label(type)} · ${e.settlement||e.district||e.region||e.derivedRegion||'місце не вказано'}`,body:`Моніторингове повідомлення · ${e.source} · ${clock(e.timestamp)}`,id:fingerprint(e)})}return[...new Map(out.map(x=>[x.id,x])).values()]}
export class NotificationAlerts{constructor(storage=localStorage){this.storage=storage;this.prefs=this.load()}load(){try{return{...DEFAULT_NOTIFICATION_PREFS,...JSON.parse(this.storage.getItem(PREF)||'{}')}}catch{return{...DEFAULT_NOTIFICATION_PREFS}}}save(next){this.prefs={...this.prefs,...next};this.storage.setItem(PREF,JSON.stringify(this.prefs));return this.prefs}baseline(){try{return JSON.parse(this.storage.getItem(BASE)||'null')}catch{return null}}prime(snapshot){this.storage.setItem(BASE,JSON.stringify(minify(snapshot)))}async enable(){if(!('Notification'in window))return'unsupported';const permission=await Notification.requestPermission();this.save({enabled:permission==='granted'});return permission}async process(snapshot,place){const previous=this.baseline(),current=minify(snapshot),items=deriveNotificationCandidates(previous,current,place,this.prefs);this.storage.setItem(BASE,JSON.stringify(current));if(this.prefs.quietNight&&isNight()&&!items.some(x=>x.official))return[];for(const item of items)await this.show(item);return items}async show(item){const options={body:item.body,tag:item.id,renotify:false,icon:'./assets/icons/icon-192.png',badge:'./assets/icons/icon-192.png',data:{url:'./#skyView',official:item.official}};const reg=await navigator.serviceWorker?.getRegistration();if(reg)return reg.showNotification(item.title,options);new Notification(item.title,options)}}
function minify(s){return{alerts:(s?.alerts||[]).map(a=>({id:a.id,region:a.region,district:a.district})),events:(s?.events||[]).map(e=>({id:e.id,source:e.source,sourceEventId:e.sourceEventId,category:e.category,region:e.region,derivedRegion:e.derivedRegion,district:e.district,settlement:e.settlement,timestamp:e.timestamp})),health:s?.health||{}}}
function label(t){return{uav:'БПЛА',missile:'Ракетна / балістична загроза',kab:'КАБ',aviation:'Авіаційна активність'}[t]}
function clock(d){return d?new Intl.DateTimeFormat('uk-UA',{hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'час не передано'}
function isNight(){const h=new Date().getHours();return h>=23||h<7}
